export const article4Content = [
  "# Comment nous monitorons 15 000 sites en temps réel avec Spot",
  "",
  "## Le problème : pourquoi les solutions du marché ne suffisaient pas",
  "",
  "Quand vous gérez la connectivité de **15 000 sites** et **50 000 équipements réseau**, le monitoring n'est pas un dashboard qu'on consulte de temps en temps. C'est le **système nerveux central** de toute l'opération.",
  "",
  "Nous avons évalué les solutions du marché — Datadog, Zabbix, LibreNMS, PRTG, SolarWinds. Aucune ne répondait à nos besoins :",
  "",
  "| Critère | Solutions marché | Notre besoin |",
  "|---|---|---|",
  "| Échelle | ~10K devices | 50K+ devices |",
  "| Métriques/min | ~100K | **2M+** |",
  "| Latence alerting | 1-5 min | **< 30 sec** |",
  "| Contexte business | Générique | **Spécifique Wifirst** |",
  "| Coût à l'échelle | 💸💸💸 | Maîtrisé |",
  "| Personnalisation | Limitée | **Totale** |",
  "",
  "C'est pourquoi nous avons construit **Spot** — notre plateforme d'observabilité réseau, développée 100% en interne.",
  "",
  "## Architecture globale",
  "",
  "```",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                     EDGE (par site client)                   │",
  "│  ┌──────────────────────────────────────────────────────┐   │",
  "│  │  Spot Collector (Go binary, ~15MB RAM)               │   │",
  "│  │  ├── SNMP Poller (interfaces, CPU, mem, Wi-Fi)       │   │",
  "│  │  ├── Syslog Receiver (UDP 514)                       │   │",
  "│  │  ├── Active Tester (ping, DNS, HTTP, speedtest)      │   │",
  "│  │  ├── Wi-Fi Metrics (assoc clients, RSSI, airtime)    │   │",
  "│  │  └── Streaming Telemetry (gNMI/gRPC) [nouveaux AP]   │   │",
  "│  └──────────────────────────────┬───────────────────────┘   │",
  "└─────────────────────────────────┼───────────────────────────┘",
  "                                  │ Protobuf / gzip",
  "                                  │ via MQTT ou HTTPS",
  "                                  ▼",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                      INGESTION LAYER                         │",
  "│  ┌────────────────────────────────────────────────────┐     │",
  "│  │              Apache Kafka (3 brokers)               │     │",
  "│  │  Topics:                                            │     │",
  "│  │  ├── raw.snmp.metrics     (~800K msg/min)           │     │",
  "│  │  ├── raw.syslog.events    (~200K msg/min)           │     │",
  "│  │  ├── raw.wifi.metrics     (~600K msg/min)           │     │",
  "│  │  ├── raw.active.tests     (~100K msg/min)           │     │",
  "│  │  ├── processed.alerts     (~2K msg/min)             │     │",
  "│  │  └── processed.aggregates (~50K msg/min)            │     │",
  "│  └────────────────────────┬───────────────────────────┘     │",
  "└───────────────────────────┼─────────────────────────────────┘",
  "                            ▼",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                    PROCESSING LAYER                          │",
  "│  ┌────────────────────────────────────────────────────┐     │",
  "│  │              Apache Flink Cluster                   │     │",
  "│  │  Jobs:                                              │     │",
  "│  │  ├── MetricAggregator (1min, 5min, 1h rollups)     │     │",
  "│  │  ├── AnomalyDetector (baseline dynamique)           │     │",
  "│  │  ├── EventCorrelator (multi-source)                 │     │",
  "│  │  ├── AlertEngine (scoring + dédup)                  │     │",
  "│  │  ├── SLACalculator (uptime, perf par client)        │     │",
  "│  │  └── WiFiAnalyzer (roaming, interference, capacity) │     │",
  "│  └────────────┬──────────────┬────────────────────────┘     │",
  "└───────────────┼──────────────┼──────────────────────────────┘",
  "                ▼              ▼",
  "┌──────────────────┐  ┌──────────────────┐",
  "│  TimescaleDB     │  │  S3 (cold)       │",
  "│  (hot: 90 days)  │  │  (Parquet, 2y)   │",
  "│  ├── metrics     │  │                  │",
  "│  ├── events      │  │  Queryable via   │",
  "│  ├── alerts      │  │  Trino/Presto    │",
  "│  └── aggregates  │  │                  │",
  "└────────┬─────────┘  └──────────────────┘",
  "         │",
  "         ▼",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                       API LAYER (Go)                         │",
  "│  ├── REST API (sites, devices, metrics, alerts)             │",
  "│  ├── GraphQL (dashboard queries)                            │",
  "│  ├── WebSocket (real-time updates)                          │",
  "│  └── gRPC (internal services)                               │",
  "└─────────────────────────┬───────────────────────────────────┘",
  "                          ▼",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                    FRONTEND (React/TypeScript)                │",
  "│  ├── Dashboard global (carte de France, KPIs)               │",
  "│  ├── Vue site (topologie, métriques, clients)               │",
  "│  ├── Vue device (détail AP/switch, historique)              │",
  "│  ├── Alerting center (triage, acquittement, escalade)       │",
  "│  └── Reports (SLA, capacity planning, tendances)            │",
  "└─────────────────────────────────────────────────────────────┘",
  "```",
  "",
  "## Le Spot Collector : notre agent edge",
  "",
  "Le Spot Collector est un binaire Go minimaliste qui tourne sur chaque CPE (routeur/passerelle) client. Contraintes de design :",
  "",
  "- **< 15 MB RAM** — les CPE ont des ressources limitées",
  "- **< 2% CPU** — ne pas impacter le forwarding",
  "- **Résilient** — doit survivre aux reboots, pertes de connectivité",
  "- **Auto-updateable** — via notre pipeline de déploiement Ansible",
  "",
  "```go",
  "// Extrait simplifié du collector (Go)",
  "type Collector struct {",
  "    pollers    []Poller",
  "    buffer     *RingBuffer    // Buffer local en cas de perte de connectivité",
  "    transport  Transport      // MQTT ou HTTPS selon le site",
  "    compress   bool           // Protobuf + gzip",
  "}",
  "",
  "func (c *Collector) Run(ctx context.Context) error {",
  "    ticker := time.NewTicker(60 * time.Second)",
  "    defer ticker.Stop()",
  "    ",
  "    for {",
  "        select {",
  "        case <-ticker.C:",
  "            metrics := c.collectAll()",
  "            ",
  "            batch := &MetricBatch{",
  "                SiteID:    c.siteID,",
  "                Timestamp: time.Now().UnixMilli(),",
  "                Metrics:   metrics,",
  "            }",
  "            ",
  "            encoded, _ := proto.Marshal(batch)",
  "            compressed := gzip.Compress(encoded)",
  "            ",
  "            if err := c.transport.Send(compressed); err != nil {",
  "                // Perte de connectivité → buffer local",
  "                c.buffer.Push(compressed)",
  '                log.Warn("buffered locally", "size", c.buffer.Len())',
  "            }",
  "            ",
  "        case <-ctx.Done():",
  "            return c.flush() // Envoyer le buffer restant",
  "        }",
  "    }",
  "}",
  "```",
  "",
  "### Gestion de la perte de connectivité",
  "",
  "Un point crucial : nos collectors tournent sur des sites dont **la connectivité peut tomber**. Le ring buffer local stocke jusqu'à 4h de métriques. À la reconnexion, les données sont renvoyées avec leur timestamp original — pas de trou dans les graphes.",
  "",
  "```",
  "Timeline de perte de connectivité :",
  "────────────────────────────────────────────────",
  "[10:00] Collecte normale → envoi Kafka ✅",
  "[10:01] Collecte normale → envoi Kafka ✅",
  "[10:02] WAN DOWN → buffer local 💾",
  "[10:03] buffer local 💾 (2 batches)",
  "[10:04] buffer local 💾 (3 batches)",
  "...",
  "[11:15] WAN UP → flush buffer (73 batches) → Kafka ✅",
  "[11:16] Collecte normale → envoi Kafka ✅",
  "────────────────────────────────────────────────",
  "Résultat : zéro perte de données, graphes continus",
  "```",
  "",
  "## Le moteur d'alerting intelligent",
  "",
  "### Le problème du bruit",
  "",
  "Avec 50 000 équipements et des seuils classiques, on obtenait **~3 000 alertes/jour**. Impossible à traiter pour une équipe NOC de 8 personnes. 90% étaient du bruit.",
  "",
  "### Notre approche : le scoring multi-facteurs",
  "",
  "Chaque événement passe par un **moteur de scoring** qui pondère plusieurs dimensions :",
  "",
  "```",
  "Score final = Σ (facteur × poids)",
  "",
  "Facteurs :",
  "──────────────────────────────────────────────────────",
  "Sévérité technique        │ Poids: 0.25",
  "  - AP down = 80          │",
  "  - Interface flapping = 60│",
  "  - CPU > 90% = 40        │",
  "                           │",
  "Impact business            │ Poids: 0.35",
  "  - Nb utilisateurs       │",
  "    affectés (0-100)       │",
  "  - Type de site (VIP=2x) │",
  "                           │",
  "Contexte temporel          │ Poids: 0.15",
  "  - Heure ouvrable = 100  │",
  "  - Nuit = 30             │",
  "  - Maintenance = 0       │",
  "                           │",
  "Historique                 │ Poids: 0.15",
  "  - Site stable = 100     │",
  "  - Site instable = 40    │",
  "  - Déjà alerté = 10      │",
  "                           │",
  "Corrélation                │ Poids: 0.10",
  "  - Événement isolé = 80  │",
  "  - Événement corrélé     │",
  "    (panne opérateur) = 20 │",
  "──────────────────────────────────────────────────────",
  "",
  "Seuils :",
  "  Score > 70 → P1 (page immédiate)",
  "  Score > 50 → P2 (ticket urgent)",
  "  Score > 30 → P3 (ticket normal)",
  "  Score < 30 → Log only (pas d'alerte)",
  "```",
  "",
  "#### Exemple concret : la même panne, deux scores différents",
  "",
  "```",
  "Événement : AP down",
  "",
  "Scénario A — Hôtel 5★ Paris, 14h, 45 clients connectés, site stable",
  "  Sévérité:    80 × 0.25 = 20.0",
  "  Impact:      90 × 0.35 = 31.5  (45 clients, VIP)",
  "  Temporel:   100 × 0.15 = 15.0  (heure ouvrable)",
  "  Historique: 100 × 0.15 = 15.0  (site stable)",
  "  Corrélation: 80 × 0.10 =  8.0  (isolé)",
  "  ─────────────────────────────",
  "  TOTAL = 89.5 → P1 🔴 Page immédiate",
  "",
  "Scénario B — Camping fermé, 3h du matin, 0 clients, site instable",
  "  Sévérité:    80 × 0.25 = 20.0",
  "  Impact:       5 × 0.35 =  1.75 (0 clients, non-VIP)",
  "  Temporel:    30 × 0.15 =  4.5  (nuit)",
  "  Historique:  40 × 0.15 =  6.0  (instable)",
  "  Corrélation: 80 × 0.10 =  8.0  (isolé)",
  "  ─────────────────────────────",
  "  TOTAL = 40.25 → P3 📋 Ticket normal",
  "```",
  "",
  "**Même événement technique, réponse totalement différente.** C'est ça, le contexte business.",
  "",
  "### Résultat : -90% de bruit",
  "",
  "```",
  "Alertes par jour (médiane glissante 30 jours) :",
  "────────────────────────────────────────────────",
  "Avant scoring : ████████████████████████████  3 200",
  "Après scoring : ███                            320",
  "  dont P1     : █                               42",
  "  dont P2     : █                               98",
  "  dont P3     : █                              180",
  "────────────────────────────────────────────────",
  "Taux de faux positifs : 8% (vs 91% avant)",
  "```",
  "",
  "## TimescaleDB : le choix du stockage time-series",
  "",
  "### Pourquoi TimescaleDB plutôt que InfluxDB ou Prometheus ?",
  "",
  "| Critère | TimescaleDB | InfluxDB | Prometheus |",
  "|---|---|---|---|",
  "| Langage de requête | **SQL** (natif) | InfluxQL/Flux | PromQL |",
  "| Compression | Excellente | Bonne | Très bonne |",
  "| Joins avec data relationnelle | ✅ natif | ❌ | ❌ |",
  "| Continuous aggregates | ✅ matérialisés | Limité | Recording rules |",
  "| Rétention flexible | ✅ par hypertable | ✅ | ✅ |",
  "| Écosystème | PostgreSQL | Propriétaire | CNCF |",
  "| Haute dispo | Patroni/streaming | Enterprise $$ | Thanos/Cortex |",
  "",
  "Le choix de TimescaleDB s'est imposé pour une raison principale : **c'est du PostgreSQL**. Notre équipe connaît SQL, nos outils parlent SQL, et pouvoir JOINer des métriques avec des données de notre CMDB (sites, clients, contrats) dans la même requête est un game-changer.",
  "",
  "```sql",
  "-- Exemple : sites avec le plus de dégradation Wi-Fi cette semaine",
  "-- corrélé avec les données client de Netbox",
  "SELECT ",
  "    s.name AS site_name,",
  "    s.client_name,",
  "    s.contract_type,",
  "    AVG(m.value) AS avg_airtime_pct,",
  "    COUNT(DISTINCT m.device_id) AS affected_aps,",
  "    s.total_users",
  "FROM metrics m",
  "JOIN sites s ON m.site_id = s.id",
  "WHERE m.metric_name = 'wifi.airtime.utilization'",
  "  AND m.time > NOW() - INTERVAL '7 days'",
  "  AND m.value > 80  -- airtime > 80% = problème",
  "GROUP BY s.id, s.name, s.client_name, s.contract_type, s.total_users",
  "HAVING COUNT(DISTINCT m.device_id) > 2  -- au moins 3 AP touchés",
  "ORDER BY s.total_users DESC  -- prioriser par impact",
  "LIMIT 20;",
  "```",
  "",
  "### Schéma et compression",
  "",
  "```sql",
  "-- Hypertable principale",
  "CREATE TABLE metrics (",
  "    time        TIMESTAMPTZ NOT NULL,",
  "    site_id     INT NOT NULL,",
  "    device_id   INT NOT NULL,",
  "    metric_name TEXT NOT NULL,",
  "    value       DOUBLE PRECISION,",
  "    tags        JSONB",
  ");",
  "",
  "SELECT create_hypertable('metrics', 'time',",
  "    chunk_time_interval => INTERVAL '1 day');",
  "",
  "-- Compression après 7 jours",
  "ALTER TABLE metrics SET (",
  "    timescaledb.compress,",
  "    timescaledb.compress_segmentby = 'site_id, device_id, metric_name',",
  "    timescaledb.compress_orderby = 'time'",
  ");",
  "",
  "SELECT add_compression_policy('metrics', INTERVAL '7 days');",
  "",
  "-- Continuous aggregate pour les dashboards",
  "CREATE MATERIALIZED VIEW metrics_hourly",
  "WITH (timescaledb.continuous) AS",
  "SELECT ",
  "    time_bucket('1 hour', time) AS bucket,",
  "    site_id, device_id, metric_name,",
  "    AVG(value) AS avg_val,",
  "    MAX(value) AS max_val,",
  "    MIN(value) AS min_val,",
  "    COUNT(*) AS sample_count",
  "FROM metrics",
  "GROUP BY bucket, site_id, device_id, metric_name;",
  "```",
  "",
  "**Taux de compression moyen : 15:1** — 2 To de données brutes → 130 Go compressées.",
  "",
  "## Ce qu'on a appris en 3 ans",
  "",
  "### 1. Les métriques brutes ne suffisent pas",
  "",
  "Un graphe CPU à 95% ne dit rien si on ne sait pas qu'il s'agit d'un switch qui sert 200 utilisateurs dans un hôtel VIP pendant un congrès. **Le contexte business est roi.**",
  "",
  "### 2. L'observabilité, ce n'est pas que des métriques",
  "",
  "Spot ingère 3 types de signaux :",
  "",
  "```",
  "┌─────────────────────────────────────────────┐",
  "│           Les 3 piliers de l'observabilité   │",
  "├───────────────┬──────────────┬──────────────┤",
  "│   Métriques   │    Logs      │   Traces     │",
  "│               │              │              │",
  "│ SNMP, gNMI    │ Syslog       │ Flux réseau  │",
  "│ Wi-Fi stats   │ Auth logs    │ Transactions │",
  "│ Active tests  │ Config diff  │ API calls    │",
  "│               │              │              │",
  "│ → TimescaleDB │ → Loki       │ → Tempo      │",
  "└───────────────┴──────────────┴──────────────┘",
  "```",
  "",
  "La corrélation entre ces 3 types est ce qui permet de passer de \"quelque chose ne va pas\" à \"voici exactement ce qui s'est passé\".",
  "",
  "### 3. Investir dans le self-healing",
  "",
  "L'étape suivante après la détection, c'est la remédiation automatique. Aujourd'hui, **35% de nos incidents P3** sont résolus automatiquement sans intervention humaine :",
  "",
  "```",
  "Actions de remédiation automatiques :",
  "──────────────────────────────────────",
  "AP non-répondant     → Reboot distant via SNMP/SSH",
  "Port en err-disable  → Bounce automatique + ticket",
  "Client en boucle auth→ Clear session RADIUS + re-auth",
  "Canal Wi-Fi saturé   → Changement canal automatique",
  "Lien WAN dégradé     → Bascule backup + notification",
  "```",
  "",
  "### 4. Le coût de la dette technique",
  "",
  "Spot a 3 ans. Certains choix initiaux nous rattrapent :",
  "",
  "- Le premier schéma TimescaleDB n'avait pas de partitionnement par site → requêtes lentes sur les gros clients. Migré en 2024.",
  "- Le format de sérialisation était JSON au début → passage à Protobuf a réduit la bande passante de 60%.",
  "- Le frontend initial en Vue.js a été réécrit en React pour s'aligner avec le reste de l'équipe.",
  "",
  "**Leçon** : les choix d'architecture initiaux ont un impact énorme à l'échelle. Prenez le temps de bien les faire.",
  "",
  "## Chiffres clés de Spot en production",
  "",
  "| Métrique | Valeur |",
  "|---|---|",
  "| Sites monitorés | 15 200 |",
  "| Devices monitorés | 52 400 |",
  "| Métriques ingérées/min | 2,1 millions |",
  "| Events/jour | 45 millions |",
  "| Latence P99 ingestion | 850 ms |",
  "| Latence P99 alerting | 12 sec |",
  "| Disponibilité Spot (12 mois) | 99,97% |",
  "| Stockage hot (90j) | 8,2 To |",
  "| Stockage cold (2 ans) | 42 To |",
  "| Coût infra mensuel | ~4 200€ |",
  "",
  "À comparer avec une estimation Datadog pour le même volume : **~35 000€/mois**. Le build vs buy est clairement en notre faveur à cette échelle.",
  "",
  "## What's next",
  "",
  "Les prochaines évolutions de Spot :",
  "",
  "- **AIOps** — Détection d'anomalies par ML (isolation forest, LSTM pour les séries temporelles)",
  "- **Predictive maintenance** — Anticiper les pannes de hardware avant qu'elles surviennent",
  "- **Root Cause Analysis automatisée** — Graphe de dépendances + propagation causale",
  "- **OpenTelemetry** — Migration progressive vers les standards OTel pour l'instrumentation",
  "",
  "---",
  "",
  "*Article rédigé par David Berkowicz, CTO Wifirst — Juin 2025*",
].join("\\n");
