#!/usr/bin/env npx tsx
import { initializeApp } from "firebase/app";
import { getFirestore, doc, setDoc, Timestamp } from "firebase/firestore";

const app = initializeApp({
  apiKey: "AIzaSyDF7sggsBkCZxl_9IcZP_K7thbsymcqGfE",
  authDomain: "wifirst-tech-blog.firebaseapp.com",
  projectId: "wifirst-tech-blog",
  storageBucket: "wifirst-tech-blog.firebasestorage.app",
  messagingSenderId: "859792971226",
  appId: "1:859792971226:web:18e02c03db7d00c5e95ce3",
});

const db = getFirestore(app);

// ─────────────────────────────────────────────────
// Article 1: Bienvenue
// ─────────────────────────────────────────────────
const article1Content = [
  "# Bienvenue sur le blog tech Wifirst",
  "",
  "## Qui sommes-nous ?",
  "",
  "**Wifirst** est le leader français du Wi-Fi managé. Depuis plus de 20 ans, nous concevons, déployons et opérons des réseaux Wi-Fi à grande échelle pour des environnements exigeants : résidences étudiantes, hôtels, résidences seniors, campings, entreprises, et bien d'autres.",
  "",
  "Notre mission est simple en apparence, mais redoutablement complexe en pratique : **fournir une connectivité fiable, performante et sécurisée à des millions d'utilisateurs, 24h/24, 7j/7**.",
  "",
  "### Quelques chiffres qui donnent le vertige",
  "",
  "| Indicateur | Valeur |",
  "|---|---|",
  "| Sites connectés | 15 000+ |",
  "| Équipements réseau gérés | 50 000+ |",
  "| Utilisateurs actifs quotidiens | 500 000+ |",
  "| Métriques ingérées par minute | ~2 millions |",
  "| Uptime SLA moyen | 99,9% |",
  "| Déploiements réseau par mois | 350+ |",
  "",
  "Ce n'est pas du cloud computing dans un datacenter climatisé. C'est du réseau **dans le monde réel** : des bâtiments anciens avec des murs en pierre, des hôtels en bord de mer avec de l'humidité saline, des résidences étudiantes où 500 personnes lancent Netflix à 20h pile.",
  "",
  "## Pourquoi ce blog ?",
  "",
  "L'équipe tech de Wifirst fait face à des problématiques techniques passionnantes que peu d'entreprises rencontrent à cette échelle en France. Pourtant, nous partageons rarement notre expertise publiquement. **Ce blog change la donne.**",
  "",
  "Nos objectifs :",
  "",
  "1. **Partager nos retours d'expérience** — les succès comme les galères",
  "2. **Contribuer à la communauté** — réseau, DevOps, sécurité, observabilité",
  "3. **Attirer des talents** — montrer ce qu'on fait vraiment au quotidien",
  "4. **Documenter nos choix techniques** — pour nous-mêmes et pour les autres",
  "",
  "### Ce que vous trouverez ici",
  "",
  "- 📡 **Wi-Fi & Radio** — Déploiements Wi-Fi 6E, planification radio, roaming, band steering",
  "- 🔐 **Sécurité** — Zero Trust, 802.1X, NAC, micro-segmentation, conformité PCI-DSS",
  "- 📊 **Observabilité** — Notre plateforme Spot, monitoring temps réel, alerting intelligent",
  "- 🤖 **Automatisation** — Ansible, NetDevOps, CI/CD réseau, Infrastructure as Code",
  "- 🏗️ **Architecture** — Design de réseaux à grande échelle, haute disponibilité, résilience",
  "",
  "## L'équipe tech",
  "",
  "Notre équipe technique est organisée en squads pluridisciplinaires :",
  "",
  "```",
  "┌─────────────────────────────────────────────────────┐",
  "│                    CTO — David B.                    │",
  "├──────────┬──────────┬──────────┬───────────┬────────┤",
  "│ NetDev   │ Platform │ Security │ Radio     │ Data   │",
  "│ Squad    │ Squad    │ Squad    │ Squad     │ Squad  │",
  "├──────────┼──────────┼──────────┼───────────┼────────┤",
  "│ Ansible  │ Spot     │ Zero     │ Wi-Fi     │ ML &   │",
  "│ Netbox   │ API      │ Trust    │ Planning  │ BI     │",
  "│ CI/CD    │ Frontend │ RADIUS   │ RF Eng.   │ Kafka  │",
  "│ Terraform│ Infra    │ Audit    │ Spectrum  │ Flink  │",
  "└──────────┴──────────┴──────────┴───────────┴────────┘",
  "```",
  "",
  "### Notre culture technique",
  "",
  "- **Infrastructure as Code** — Tout est versionné, tout est reproductible",
  "- **Ownership** — Chaque squad est responsable de bout en bout (build + run)",
  "- **Blameless post-mortems** — On apprend de nos erreurs, on ne cherche pas de coupables",
  "- **Open source first** — On contribue quand on peut (Ansible collections, monitoring plugins)",
  "- **Documentation** — Si ce n'est pas documenté, ça n'existe pas",
  "",
  "### Notre stack technique",
  "",
  "```",
  "┌─── Frontend ──────────────────────────────┐",
  "│  React / Next.js / TypeScript             │",
  "├─── Backend ───────────────────────────────┤",
  "│  Go (API) / Python (data) / Rust (perf)   │",
  "├─── Data Pipeline ─────────────────────────┤",
  "│  Kafka → Flink → TimescaleDB / S3         │",
  "├─── Infra ─────────────────────────────────┤",
  "│  Kubernetes / Terraform / Ansible         │",
  "├─── Réseau ────────────────────────────────┤",
  "│  Netbox (CMDB) / RADIUS / SNMP / gNMI    │",
  "├─── Observabilité ─────────────────────────┤",
  "│  Spot (maison) / Prometheus / Grafana     │",
  "└───────────────────────────────────────────┘",
  "```",
  "",
  "## Les défis qui nous passionnent",
  "",
  "### 1. L'échelle",
  "",
  "Gérer 50 000 équipements réseau, ce n'est pas juste \"du monitoring\". C'est construire des systèmes capables d'ingérer 2 millions de métriques par minute, de détecter une anomalie en quelques secondes, et de déclencher une action corrective avant même que l'utilisateur ne s'en rende compte.",
  "",
  "### 2. La diversité des environnements",
  "",
  "Chaque site est unique. Un hôtel 5 étoiles à Paris n'a pas les mêmes contraintes qu'un camping en Bretagne ou qu'une résidence étudiante à Lyon. Notre plateforme doit être suffisamment flexible pour s'adapter, tout en restant standardisée pour être opérable à l'échelle.",
  "",
  "### 3. Le temps réel",
  "",
  "Quand un client d'hôtel appelle la réception parce que le Wi-Fi ne marche pas, le problème doit être détecté et résolu **en minutes, pas en heures**. C'est un défi d'ingénierie qui touche à la collecte de données, au traitement temps réel, à l'automatisation des remédiation, et à l'UX de nos outils internes.",
  "",
  "### 4. La sécurité à l'échelle",
  "",
  "Gérer des réseaux pour des milliers de clients avec des millions d'utilisateurs, c'est une responsabilité immense en termes de sécurité. Zero Trust, segmentation, conformité RGPD, PCI-DSS pour le retail... chaque couche ajoute de la complexité.",
  "",
  "## Ce qui arrive",
  "",
  "Dans les prochaines semaines, vous découvrirez sur ce blog :",
  "",
  "- **Wi-Fi 6E à grande échelle** — Notre retour d'expérience sur le déploiement de la bande 6 GHz",
  "- **Zero Trust réseau** — Comment nous avons repensé la sécurité de bout en bout",
  "- **Spot, notre plateforme de monitoring** — Architecture et défis d'un outil maison",
  "- **NetDevOps avec Ansible** — Notre pipeline d'automatisation LAN",
  "",
  "Chaque article sera technique, concret, avec du code et des schémas. Pas de marketing fluff, que de l'ingénierie.",
  "",
  "## Rejoignez-nous !",
  "",
  "Si ces sujets vous parlent, si vous aimez résoudre des problèmes complexes à grande échelle, et si vous voulez travailler dans une équipe qui valorise l'excellence technique — **on recrute** !",
  "",
  "```bash",
  '# Notre process de recrutement en une ligne',
  'echo "CV" | review | entretien_technique | pair_programming | offre 🎉',
  "```",
  "",
  "Consultez nos offres sur [wifirst.com/careers](https://wifirst.com) ou envoyez-nous directement un message.",
  "",
  "---",
  "",
  "*Bonne lecture, et bienvenue dans les coulisses tech de Wifirst !*",
  "",
  "— **David Berkowicz**, CTO Wifirst",
].join("\n");

// ─────────────────────────────────────────────────
// Article 2: Wi-Fi 6E
// ─────────────────────────────────────────────────
const article2Content = [
  "# Wi-Fi 6E : retour d'expérience sur un déploiement à grande échelle",
  "",
  "## Introduction : pourquoi le Wi-Fi 6E change tout",
  "",
  "Le Wi-Fi 6E (IEEE 802.11ax étendu à la bande 6 GHz) n'est pas une simple évolution incrémentale. C'est un **changement de paradigme** pour les réseaux sans fil haute densité. En ouvrant jusqu'à **1200 MHz de spectre vierge** dans la bande 5925–7125 MHz, le Wi-Fi 6E résout le problème fondamental qui plaguait les déploiements Wi-Fi depuis des années : **le manque de spectre**.",
  "",
  "Chez Wifirst, nous avons lancé début 2025 un programme ambitieux de migration Wi-Fi 6E sur notre parc. Cet article est un retour d'expérience brut, avec les chiffres réels, les galères et les victoires.",
  "",
  "## Rappel : Wi-Fi 6 vs Wi-Fi 6E vs Wi-Fi 7",
  "",
  "| Caractéristique | Wi-Fi 6 (802.11ax) | Wi-Fi 6E (802.11ax) | Wi-Fi 7 (802.11be) |",
  "|---|---|---|---|",
  "| Bandes | 2,4 + 5 GHz | 2,4 + 5 + **6 GHz** | 2,4 + 5 + 6 GHz |",
  "| Largeur max canal | 160 MHz | **160 MHz** | **320 MHz** |",
  "| Spectre 6 GHz | ❌ | **1200 MHz** | 1200 MHz |",
  "| Canaux 160 MHz dispo | 2 (5 GHz) | **7** (6 GHz) | 7+ (avec 320) |",
  "| Modulation max | 1024-QAM | 1024-QAM | **4096-QAM** |",
  "| OFDMA | ✅ | ✅ | ✅ amélioré |",
  "| MU-MIMO | 8×8 | 8×8 | **16×16** |",
  "| MLO | ❌ | ❌ | ✅ |",
  "| Débit théorique max | 9,6 Gbps | 9,6 Gbps | **46 Gbps** |",
  "",
  "### Le spectre 6 GHz en détail",
  "",
  "```",
  "Bande 5 GHz (existante) :",
  "├── UNII-1: 5150-5250 MHz  (100 MHz, 5 canaux 20MHz)",
  "├── UNII-2: 5250-5350 MHz  (100 MHz, 5 canaux 20MHz)",
  "├── UNII-2e: 5470-5725 MHz (255 MHz, 12 canaux 20MHz)",
  "└── UNII-3: 5725-5850 MHz  (125 MHz, 5 canaux 20MHz)",
  "    Total: ~580 MHz, 25 canaux 20MHz, 2 canaux 160MHz",
  "",
  "Bande 6 GHz (Wi-Fi 6E) :",
  "├── UNII-5: 5925-6425 MHz  (500 MHz, 24 canaux 20MHz)",
  "├── UNII-6: 6425-6525 MHz  (100 MHz, 5 canaux 20MHz)",
  "├── UNII-7: 6525-6875 MHz  (350 MHz, 17 canaux 20MHz)",
  "└── UNII-8: 6875-7125 MHz  (250 MHz, 12 canaux 20MHz)",
  "    Total: 1200 MHz, 59 canaux 20MHz, 7 canaux 160MHz",
  "```",
  "",
  "**En résumé** : le 6 GHz offre **plus du double** du spectre disponible en 5 GHz, dans une bande totalement vierge — aucun appareil legacy, aucune interférence existante.",
  "",
  "## Notre programme de migration",
  "",
  "### Phase 1 — Audit et planification (2 mois)",
  "",
  "Avant de toucher au moindre AP, nous avons mené un audit complet :",
  "",
  "1. **Inventaire du parc existant** — 12 400 AP en service, dont 8 200 compatibles Wi-Fi 6",
  "2. **Analyse du parc client** — Pourcentage de devices 6E-compatibles par type de site",
  "3. **Études de propagation 6 GHz** — Modélisation de l'atténuation supplémentaire",
  "4. **Évaluation réglementaire** — Contraintes AFC en France (ARCEP/ANFR)",
  "",
  "#### Compatibilité des terminaux — le reality check",
  "",
  "```",
  "Taux de devices Wi-Fi 6E par segment (Q1 2025) :",
  "──────────────────────────────────────────────",
  "Résidences étudiantes : ████████████░░░░░░  62%",
  "Hôtels business       : ██████████░░░░░░░░  55%",
  "Hôtels loisirs        : ██████░░░░░░░░░░░░  35%",
  "Résidences seniors    : ███░░░░░░░░░░░░░░░  18%",
  "Campings              : ████░░░░░░░░░░░░░░  22%",
  "──────────────────────────────────────────────",
  "Moyenne globale       : ████████░░░░░░░░░░  42%",
  "```",
  "",
  "Ce n'est pas une surprise : les étudiants sont early adopters, les seniors moins. Cela a directement impacté notre stratégie de déploiement — **les résidences étudiantes en priorité**.",
  "",
  "### Phase 2 — Conception radio (1 mois)",
  "",
  "#### Atténuation 6 GHz vs 5 GHz",
  "",
  "La fréquence plus élevée du 6 GHz implique une atténuation plus importante à travers les matériaux :",
  "",
  "| Matériau | Atténuation 5 GHz | Atténuation 6 GHz | Delta |",
  "|---|---|---|---|",
  "| Placo standard | 3 dB | 4 dB | +1 dB |",
  "| Placo double | 6 dB | 8 dB | +2 dB |",
  "| Béton (15 cm) | 15 dB | 19 dB | +4 dB |",
  "| Brique | 8 dB | 11 dB | +3 dB |",
  "| Verre simple | 4 dB | 5 dB | +1 dB |",
  "| Porte coupe-feu | 13 dB | 17 dB | +4 dB |",
  "",
  "**Conséquence** : une réduction de **15-20% du rayon de couverture** par rapport au 5 GHz dans nos environnements types. La densification nécessaire est d'environ **1.2x** — pour 10 AP 5 GHz, il faut prévoir 12 AP pour une couverture 6 GHz équivalente.",
  "",
  "#### Stratégie tri-bande",
  "",
  "Notre design radio repose sur une architecture tri-bande avec rôles différenciés :",
  "",
  "```",
  '┌─────────────────────────────────────────────────┐',
  '│               SSID unifié "Wifirst"             │',
  '├───────────┬─────────────────┬───────────────────┤',
  '│  2,4 GHz  │     5 GHz       │     6 GHz         │',
  '│  Legacy   │   Mainstream    │   Performance      │',
  '│           │                 │                    │',
  '│ IoT, vieux│ Majorité des    │ Devices récents,   │',
  '│ devices   │ clients         │ haute densité      │',
  '│           │                 │                    │',
  '│ 20 MHz    │ 40/80 MHz       │ 80/160 MHz         │',
  '│ canaux    │ canaux          │ canaux             │',
  '├───────────┼─────────────────┼───────────────────┤',
  '│ Band steering intelligent (11v/11k/11r)         │',
  '│ + détection capacité client → assignation bande │',
  '└─────────────────────────────────────────────────┘',
  "```",
  "",
  "### Phase 3 — AFC (Automated Frequency Coordination)",
  "",
  "En France, la réglementation ARCEP impose l'utilisation d'un système AFC pour les déploiements 6 GHz indoor à puissance élevée (Low Power Indoor — LPI — est exempt). Nous avons développé un **client AFC maison** :",
  "",
  "```python",
  "# Extrait simplifié de notre client AFC",
  "class AFCClient:",
  '    """Client AFC pour l\'enregistrement auprès de l\'ANFR."""',
  "    ",
  "    def __init__(self, api_url: str, credentials: dict):",
  "        self.api_url = api_url",
  "        self.session = self._authenticate(credentials)",
  "    ",
  "    def request_spectrum(self, ap_location: GeoPoint, ",
  "                         desired_channels: list[int],",
  "                         max_eirp_dbm: float = 24.0) -> AFCResponse:",
  '        """',
  "        Demande d'autorisation spectrale pour un AP.",
  "        Retourne les canaux autorisés et la puissance max.",
  '        """',
  "        payload = {",
  '            "version": "1.4",',
  '            "availableSpectrumInquiryRequests": [{',
  '                "requestId": str(uuid4()),',
  '                "deviceDescriptor": {',
  '                    "serialNumber": self.ap_serial,',
  '                    "certificationId": [{"id": "FR-AFC-2025-001"}]',
  "                },",
  '                "location": {',
  '                    "ellipse": {',
  '                        "center": {',
  '                            "latitude": ap_location.lat,',
  '                            "longitude": ap_location.lng',
  "                        },",
  '                        "majorAxis": 50,',
  '                        "minorAxis": 50',
  "                    },",
  '                    "height": ap_location.floor * 3.0,',
  '                    "heightType": "AGL"',
  "                },",
  '                "inquiredChannels": [',
  '                    {"globalOperatingClass": 131, "channelCfi": desired_channels}',
  "                ],",
  '                "maxEirp": max_eirp_dbm',
  "            }]",
  "        }",
  '        return self._post("/availableSpectrumInquiry", payload)',
  "```",
  "",
  "### Phase 4 — Déploiement et résultats",
  "",
  "Sur 6 mois, nous avons migré **547 sites** vers le Wi-Fi 6E. Voici les résultats mesurés sur le terrain :",
  "",
  "#### Performances comparées (mesures terrain, médiane sur 547 sites)",
  "",
  "| Métrique | 5 GHz (80 MHz) | 6 GHz (160 MHz) | Amélioration |",
  "|---|---|---|---|",
  "| Débit DL médian | 380 Mbps | 820 Mbps | **+116%** |",
  "| Débit UL médian | 95 Mbps | 210 Mbps | **+121%** |",
  "| Latence P50 | 8 ms | 2 ms | **-75%** |",
  "| Latence P95 | 14 ms | 5 ms | **-64%** |",
  "| Airtime utilization | 62% | 28% | **-55%** |",
  "| Capacité clients/AP | 65 | 130 | **+100%** |",
  "| Taux de roaming échoué | 2,8% | 0,9% | **-68%** |",
  "",
  "#### Impact sur l'expérience utilisateur",
  "",
  "```",
  "Score NPS Wi-Fi (résidences étudiantes, n=12000) :",
  "─────────────────────────────────────────────────",
  "Avant 6E (2024 S2) :  ██████████████░░░░░░  +32",
  "Après 6E (2025 S1) :  ████████████████████  +58",
  "─────────────────────────────────────────────────",
  "                       Δ = +26 points NPS 🎉",
  "```",
  "",
  "## Les galères (parce qu'il y en a eu)",
  "",
  "### 1. Le driver Intel AX211 et le DFS",
  "",
  "Certains laptops avec la carte Intel AX211 avaient un bug de driver qui provoquait des déconnexions lors du DFS (Dynamic Frequency Selection) sur certains canaux 6 GHz. Solution : blacklist de 3 canaux spécifiques dans notre contrôleur et remontée du bug à Intel.",
  "",
  "### 2. Apple et le Preferred Scanning",
  "",
  "Les iPhones/iPads avec iOS 17 avaient un comportement agressif de \"preferred scanning\" qui les faisait rester sur le 5 GHz même quand le 6 GHz était disponible et meilleur. Il a fallu ajuster nos paramètres de band steering (seuils RSSI, timers de probe response) pour contourner ce comportement.",
  "",
  "### 3. La co-existence avec les systèmes existants",
  "",
  "Certains sites avaient des systèmes DECT (téléphonie sans fil) qui interféraient marginalement avec le bas de la bande UNII-5. Solution : exclusion des canaux 1-5 sur ces sites.",
  "",
  "## Planification radio avancée : notre méthodologie",
  "",
  "### Modélisation prédictive de couverture",
  "",
  "Nous utilisons un outil de planification radio interne qui intègre les plans architecturaux des bâtiments et les caractéristiques d'atténuation des matériaux. Le processus suit 4 étapes :",
  "",
  "```",
  "┌──────────────────────────────────────────────────────┐",
  "│           Pipeline de planification radio             │",
  "├──────────────────────────────────────────────────────┤",
  "│                                                       │",
  "│  1. Import plan CAD/PDF                               │",
  "│     ↓                                                 │",
  "│  2. Classification murs (béton/placo/verre)           │",
  "│     ↓                                                 │",
  "│  3. Placement AP (algo génétique + contraintes)       │",
  "│     ↓                                                 │",
  "│  4. Simulation propagation (ray-tracing simplifié)    │",
  "│     ↓                                                 │",
  "│  5. Validation terrain (survey post-install)          │",
  "│                                                       │",
  "│  Précision modèle vs terrain : ±3 dB (P90)           │",
  "└──────────────────────────────────────────────────────┘",
  "```",
  "",
  "### Gestion du roaming tri-bande",
  "",
  "Le roaming dans un environnement tri-bande ajoute une dimension de complexité. Notre contrôleur implémente un algorithme de steering à 3 niveaux :",
  "",
  "```python",
  "# Logique simplifiée de band steering tri-bande",
  "def select_band(client_capabilities, current_rssi, load_per_band):",
  "    if client_capabilities.supports_6ghz:",
  "        if load_per_band['6ghz'] < 0.6:  # airtime < 60%",
  "            if current_rssi['6ghz'] > -72:  # signal suffisant",
  "                return '6ghz'",
  "    ",
  "    if client_capabilities.supports_5ghz:",
  "        if load_per_band['5ghz'] < 0.7:",
  "            if current_rssi['5ghz'] > -75:",
  "                return '5ghz'",
  "    ",
  "    return '2.4ghz'  # fallback legacy",
  "```",
  "",
  "Les seuils RSSI et airtime sont ajustés dynamiquement en fonction du profil du site (haute densité vs couverture étendue).",
  "",
  "## Conclusion et perspectives Wi-Fi 7",
  "",
  "Le Wi-Fi 6E est un vrai **game-changer** pour les environnements haute densité. Nos métriques le prouvent sans ambiguïté.",
  "",
  "La prochaine étape ? **Le Wi-Fi 7 (802.11be)**, qui apportera :",
  "- **Multi-Link Operation (MLO)** — utilisation simultanée de plusieurs bandes",
  "- **Canaux 320 MHz** — encore plus de débit",
  "- **4096-QAM** — meilleure efficacité spectrale",
  "- **Multi-RU** — OFDMA amélioré",
  "",
  "Nous commençons déjà les tests en lab. Stay tuned !",
  "",
  "---",
  "",
  "*Article rédigé par l'équipe NetDev de Wifirst — Juin 2025*",
].join("\n");

// ─────────────────────────────────────────────────
// Article 3: Zero Trust
// ─────────────────────────────────────────────────
const article3Content = [
  "# Sécuriser un réseau d'entreprise : notre approche Zero Trust de A à Z",
  "",
  "## Le constat : pourquoi le modèle périmétrique est mort",
  "",
  'Le modèle de sécurité réseau traditionnel — le fameux "château fort" avec ses douves (firewall) et son pont-levis (VPN) — repose sur une hypothèse fondamentale : **ce qui est à l\'intérieur du réseau est de confiance**.',
  "",
  "Cette hypothèse est fausse. Et elle l'est de plus en plus :",
  "",
  "```",
  "Évolution de la surface d'attaque réseau (2019 → 2025) :",
  "────────────────────────────────────────────────────────",
  "Devices par site     : ██████░░░░  →  ██████████████████",
  "(postes, IoT, BYOD)   ~50              ~200",
  "",
  "Points d'entrée     : ███░░░░░░░  →  █████████████░░░░░",
  "(Wi-Fi, VPN, cloud)    ~3               ~12",
  "",
  "Flux Est-Ouest       : ████░░░░░░  →  ████████████████░░",
  "(inter-device)         faible           dominant",
  "",
  "Shadow IT            : ██░░░░░░░░  →  ███████████░░░░░░░",
  "                       rare             systémique",
  "────────────────────────────────────────────────────────",
  "```",
  "",
  "Chez Wifirst, nous opérons des réseaux pour des clients aux profils très différents — hôtels, résidences, retail, entreprises. **Le Zero Trust n'est pas un choix idéologique, c'est une nécessité opérationnelle.**",
  "",
  "## Les 5 piliers de notre architecture Zero Trust",
  "",
  "### Pilier 1 : Authentification forte — 802.1X partout",
  "",
  "Le premier principe du Zero Trust est simple : **aucun device n'accède au réseau sans s'être authentifié**. Nous implémentons 802.1X (IEEE standard pour le contrôle d'accès au réseau) sur tous les ports physiques et SSIDs.",
  "",
  "#### Architecture RADIUS",
  "",
  "```",
  "┌──────────┐     EAP      ┌──────────┐   RADIUS   ┌──────────────┐",
  "│  Client  │◄────────────►│  Switch/ │◄──────────►│   FreeRADIUS  │",
  "│ (suppl.) │  802.1X      │  AP (NAS)│            │   Cluster     │",
  "└──────────┘              └──────────┘            └──────┬───────┘",
  "                                                         │",
  "                               ┌─────────────────────────┼──────┐",
  "                               │                         │      │",
  "                          ┌────▼─────┐  ┌────────────┐  ┌▼─────┐",
  "                          │ Active   │  │ Certificate│  │Policy│",
  "                          │ Directory│  │ Authority  │  │Engine│",
  "                          └──────────┘  └────────────┘  └──────┘",
  "```",
  "",
  "#### Méthodes EAP selon le type de device",
  "",
  "```python",
  "# Logique de notre policy engine (simplifié)",
  "def assign_auth_method(device: Device) -> AuthMethod:",
  "    if device.is_managed and device.has_certificate:",
  "        # Postes d'entreprise gérés → EAP-TLS (certificat machine)",
  "        return AuthMethod.EAP_TLS",
  "    ",
  "    elif device.type == 'workstation' and device.has_credentials:",
  "        # Postes non gérés avec credentials → PEAP-MSCHAPv2",
  "        return AuthMethod.PEAP_MSCHAPV2",
  "    ",
  '    elif device.type in ("iot", "printer", "camera"):',
  "        # IoT sans supplicant 802.1X → MAB + profiling",
  "        return AuthMethod.MAB_WITH_PROFILING",
  "    ",
  '    elif device.type == "guest":',
  "        # Invités → Captive portal + SMS/email validation",
  "        return AuthMethod.CAPTIVE_PORTAL",
  "    ",
  "    else:",
  "        # Inconnu → quarantaine",
  "        return AuthMethod.QUARANTINE",
  "```",
  "",
  "| Méthode | Sécurité | Complexité | Usage |",
  "|---|---|---|---|",
  "| EAP-TLS | ★★★★★ | Élevée (PKI) | Postes gérés, serveurs |",
  "| PEAP-MSCHAPv2 | ★★★☆☆ | Moyenne | BYOD avec credentials |",
  "| EAP-TTLS | ★★★★☆ | Moyenne | Alternative à PEAP |",
  "| MAB + Profiling | ★★☆☆☆ | Faible | IoT, imprimantes |",
  "| Captive Portal | ★★☆☆☆ | Faible | Invités |",
  "",
  "### Pilier 2 : Micro-segmentation — chaque device dans sa bulle",
  "",
  "Une fois authentifié, chaque device est placé dans un **segment réseau adapté à son profil de risque**. Fini le VLAN unique \"réseau d'entreprise\".",
  "",
  "#### Matrice de segmentation",
  "",
  "```",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                    Architecture de segmentation              │",
  "├──────────────┬──────────┬────────────┬──────────────────────┤",
  "│   Segment    │  VLAN    │  Subnet    │  Politique           │",
  "├──────────────┼──────────┼────────────┼──────────────────────┤",
  "│ Corporate    │  10      │ 10.x.10/24 │ Full access, DPI     │",
  "│ BYOD         │  15      │ 10.x.15/24 │ Internet + apps auth │",
  "│ Guest        │  20      │ 10.x.20/24 │ Internet only, CPL   │",
  "│ IoT Trusted  │  30      │ 10.x.30/24 │ Whitelist dest       │",
  "│ IoT Untrusted│  31      │ 10.x.31/24 │ Strict whitelist     │",
  "│ VoIP         │  40      │ 10.x.40/24 │ QoS prioritaire      │",
  "│ PCI-DSS      │  50      │ 10.x.50/24 │ Isolé, chiffré, logs │",
  "│ Management   │  99      │ 10.x.99/24 │ Admin, MFA, jump box │",
  "│ Quarantine   │  666     │ 10.x.66/24 │ Portail remédiation  │",
  "└──────────────┴──────────┴────────────┴──────────────────────┘",
  "```",
  "",
  "#### Dynamic VLAN Assignment via RADIUS",
  "",
  "Le VLAN est assigné dynamiquement par RADIUS en fonction du résultat de l'authentification :",
  "",
  "```",
  "# Extrait de configuration FreeRADIUS (policy.d/assignment)",
  'if (&control.Auth-Type == "EAP-TLS") {',
  "    if (&TLS-Cert-Subject =~ /OU=Corporate/) {",
  "        update reply {",
  "            Tunnel-Type := VLAN",
  "            Tunnel-Medium-Type := IEEE-802",
  '            Tunnel-Private-Group-Id := "10"',
  "        }",
  "    }",
  "}",
  "",
  'if (&control.Auth-Type == "MAB") {',
  "    # Profiling result from our NAC",
  '    if (&control.Device-Profile == "IP-Camera") {',
  "        update reply {",
  '            Tunnel-Private-Group-Id := "31"',
  '            Filter-Id := "ACL-IOT-UNTRUSTED"',
  "        }",
  "    }",
  "}",
  "```",
  "",
  "### Pilier 3 : Contrôle d'accès réseau (NAC)",
  "",
  "Notre NAC va au-delà de l'authentification initiale. Il effectue un **contrôle continu de la posture** du device :",
  "",
  "```",
  "┌─────────────────────────────────────────────────────┐",
  "│              Continuous Posture Assessment           │",
  "├─────────────────────────────────────────────────────┤",
  "│                                                      │",
  "│  ┌──────────┐    ┌───────────┐    ┌──────────────┐  │",
  "│  │ Connexion │───►│ Auth      │───►│ Posture      │  │",
  "│  │ initiale  │    │ 802.1X    │    │ Check        │  │",
  "│  └──────────┘    └───────────┘    └──────┬───────┘  │",
  "│                                          │           │",
  "│                    ┌─────────────────────┤           │",
  "│                    │                     │           │",
  "│              ┌─────▼─────┐        ┌──────▼──────┐   │",
  "│              │  CONFORME  │        │NON-CONFORME │   │",
  "│              │ → Accès    │        │→ Quarantaine│   │",
  "│              │   normal   │        │  + Portail  │   │",
  "│              └─────┬──────┘        │  remédiation│   │",
  "│                    │               └─────────────┘   │",
  "│              ┌─────▼──────┐                          │",
  "│              │ Re-check   │ ← toutes les 4h          │",
  "│              │ périodique  │   ou sur événement       │",
  "│              └────────────┘                          │",
  "└─────────────────────────────────────────────────────┘",
  "```",
  "",
  "Critères de posture vérifiés :",
  "- **OS à jour** — patches de sécurité < 30 jours",
  "- **Antivirus actif** et signatures < 48h",
  "- **Firewall local** activé",
  "- **Chiffrement disque** activé (BitLocker / FileVault)",
  "- **Pas de jailbreak/root** (mobile)",
  "",
  "### Pilier 4 : Chiffrement et inspection des flux",
  "",
  "Chaque segment a sa propre politique d'inspection :",
  "",
  "```yaml",
  "# Politique d'inspection par segment (extrait)",
  "segments:",
  "  corporate:",
  "    tls_inspection: true",
  '    ids_ips: "inline"',
  '    dns_filtering: "moderate"',
  "    url_categorization: true",
  "    dlp: true    # Data Loss Prevention",
  "    ",
  "  guest:",
  "    tls_inspection: false  # Vie privée",
  '    ids_ips: "passive"',
  '    dns_filtering: "strict"  # Malware + adult + gambling',
  '    bandwidth_limit: "50Mbps"',
  '    session_timeout: "8h"',
  "    ",
  "  pci_dss:",
  "    tls_inspection: true",
  '    ids_ips: "inline_strict"',
  "    all_traffic_logged: true",
  "    allowed_destinations:",
  '      - "payment-gateway.provider.com"',
  '      - "updates.pos-vendor.com"',
  '    everything_else: "deny"',
  "```",
  "",
  "### Pilier 5 : Monitoring et réponse — boucle fermée avec Spot",
  "",
  "Notre plateforme **Spot** est le cerveau de notre architecture Zero Trust. Elle observe en permanence :",
  "",
  "- **NetFlow/sFlow** — tous les flux réseau analysés",
  "- **Anomalies comportementales** — un PC corporate qui scanne des ports ? Alerte.",
  "- **Mouvement latéral** — tentative de communication inter-VLAN non autorisée",
  "- **Exfiltration** — volumes anormaux de données sortantes",
  "- **Brute force** — tentatives répétées d'authentification",
  "",
  "```",
  "Exemple de détection : mouvement latéral",
  "─────────────────────────────────────────",
  "[14:32:15] Device 10.12.10.45 (Corporate/Laptop)",
  "           → ARP scan detected on 10.12.30.0/24 (IoT segment)",
  "[14:32:16] ALERT: Lateral movement attempt",
  "           Severity: HIGH | Impact: MEDIUM",
  "[14:32:16] AUTO-RESPONSE: CoA (Change of Authorization)",
  "           → Device moved to VLAN 666 (Quarantine)",
  "[14:32:17] TICKET: SEC-2025-4891 created",
  "           → Assigned to SOC L2",
  "[14:32:18] NOTIFICATION: Slack #security-alerts",
  "```",
  "",
  "## Cas concret : déploiement retail — 800 sites PCI-DSS",
  "",
  "### Le contexte",
  "",
  "Un client retail majeur : **800 points de vente** en France, chacun avec :",
  "- 2-4 caisses (terminaux de paiement, PCI-DSS scope)",
  "- 1-2 PC back-office",
  "- Wi-Fi invités",
  "- Caméras IP (4-8 par site)",
  "- Affichage dynamique",
  "- Divers IoT (capteurs température, compteurs de passage)",
  "",
  "### Le défi PCI-DSS",
  "",
  "La norme PCI-DSS v4.0 exige une **isolation complète** du CDE (Cardholder Data Environment) du reste du réseau. Les caisses ne doivent communiquer qu'avec le processeur de paiement, rien d'autre.",
  "",
  "### La solution déployée",
  "",
  "```",
  "                    ┌──────────────────────┐",
  "                    │     Internet /WAN     │",
  "                    └──────────┬───────────┘",
  "                               │",
  "                    ┌──────────▼───────────┐",
  "                    │   Firewall (NGFW)     │",
  "                    │   + IDS/IPS inline    │",
  "                    └──────────┬───────────┘",
  "                               │",
  "        ┌──────────────────────┼──────────────────────┐",
  "        │                      │                       │",
  "  ┌─────▼──────┐     ┌────────▼────────┐    ┌────────▼───────┐",
  "  │ VLAN 50    │     │ VLAN 10         │    │ VLAN 20        │",
  "  │ PCI-DSS    │     │ Corporate       │    │ Guest Wi-Fi    │",
  "  │            │     │                 │    │                │",
  "  │ [Caisse 1] │     │ [PC Back-off]   │    │ [Clients]      │",
  "  │ [Caisse 2] │     │ [Affichage]     │    │                │",
  "  │ [TPE]      │     │ [Caméras]       │    │ Internet only  │",
  "  │            │     │                 │    │ + captive      │",
  "  │ → Payment  │     │ → Filtered      │    │   portal       │",
  "  │   gateway  │     │   Internet      │    │                │",
  "  │   ONLY     │     │                 │    │                │",
  "  └────────────┘     └─────────────────┘    └────────────────┘",
  "     ISOLÉ              INSPECTÉ               LIMITÉ",
  "```",
  "",
  "### Résultats mesurés (après 6 mois)",
  "",
  "| Métrique | Avant Zero Trust | Après Zero Trust | Delta |",
  "|---|---|---|---|",
  "| Surface d'attaque (ports exposés) | 12 400 | 3 350 | **-73%** |",
  "| Incidents sécurité / mois | 23 | 4 | **-83%** |",
  "| Temps moyen de détection (MTTD) | 4,2h | 12 min | **-95%** |",
  "| Temps moyen de réponse (MTTR) | 6h | 45 min | **-87%** |",
  "| Score audit PCI-DSS | 72/100 | 96/100 | **+33%** |",
  "| Faux positifs alerting / jour | 180 | 22 | **-88%** |",
  "",
  "## Leçons apprises et recommandations",
  "",
  "### 1. Commencer par l'inventaire",
  "",
  '> "You can\'t secure what you can\'t see."',
  "",
  "Avant toute chose, faites un inventaire exhaustif. Nous utilisons une combinaison de :",
  "- **Scan réseau actif** (Nmap)",
  "- **Profiling passif** (fingerprinting DHCP, HTTP user-agent, OUI MAC)",
  "- **Intégration CMDB** (Netbox)",
  "",
  "### 2. Progressivité : monitor → enforce",
  "",
  "Ne passez **jamais** en enforcement du jour au lendemain. Notre roadmap type :",
  "",
  "```",
  "Semaine 1-2 : Mode MONITOR (802.1X en open mode)",
  "  → Observer qui s'authentifie, qui échoue",
  "  → Identifier les devices sans supplicant",
  "",
  "Semaine 3-4 : Mode LOW-IMPACT (VLAN par défaut pour échecs)",
  "  → Les devices non-conformes obtiennent un accès limité",
  "  → Pas de coupure brutale",
  "",
  "Semaine 5-6 : Mode ENFORCE (closed mode)",
  "  → 802.1X obligatoire",
  "  → Quarantaine pour les non-conformes",
  "  → Portail de remédiation disponible",
  "```",
  "",
  "### 3. Formation des équipes terrain",
  "",
  "Le meilleur système de sécurité ne vaut rien si les techniciens terrain le contournent. Nous avons formé **350 techniciens** sur :",
  "- Les principes du Zero Trust (le \"pourquoi\")",
  "- Le diagnostic de problèmes 802.1X",
  "- L'utilisation des outils de remédiation",
  "",
  "### 4. Exceptions documentées",
  "",
  "Il y aura **toujours** des exceptions. La clé : les documenter, les approuver formellement, et les réviser régulièrement.",
  "",
  "```yaml",
  "# Exemple de registre d'exceptions",
  "exceptions:",
  '  - id: "SEC-EXC-2025-042"',
  '    device: "Vieux thermomètre IoT"',
  '    reason: "Firmware ne supporte pas 802.1X ni MAB"',
  '    mitigation: "Port security + ACL stricte + monitoring renforcé"',
  '    approved_by: "CISO"',
  '    review_date: "2025-09-01"',
  "    risk_accepted: true",
  "```",
  "",
  "## Conclusion",
  "",
  "Le Zero Trust n'est pas un produit qu'on achète, c'est une **philosophie qu'on implémente couche par couche**. Et ça commence par le réseau — parce que le réseau voit tout, transporte tout, et contrôle tout.",
  "",
  "Les résultats parlent d'eux-mêmes : **-73% de surface d'attaque, -83% d'incidents, détection en minutes au lieu d'heures**. L'investissement en vaut la peine.",
  "",
  "---",
  "",
  "*Article rédigé par l'équipe Sécurité de Wifirst — Juin 2025*",
].join("\n");

// ─────────────────────────────────────────────────
// Article 4: Monitoring Spot
// ─────────────────────────────────────────────────
const article4Content = [
  "# Comment nous monitorons 15 000 sites en temps réel avec Spot",
  "",
  "## Le problème : pourquoi les solutions du marché ne suffisaient pas",
  "",
  "Quand vous gérez la connectivité de **15 000 sites** et **50 000 équipements réseau**, le monitoring n'est pas un dashboard qu'on consulte de temps en temps. C'est le **système nerveux central** de toute l'opération.",
  "",
  "Nous avons évalué les solutions du marché — Datadog, Zabbix, LibreNMS, PRTG, SolarWinds. Aucune ne répondait à nos besoins :",
  "",
  "| Critère | Solutions marché | Notre besoin |",
  "|---|---|---|",
  "| Échelle | ~10K devices | 50K+ devices |",
  "| Métriques/min | ~100K | **2M+** |",
  "| Latence alerting | 1-5 min | **< 30 sec** |",
  "| Contexte business | Générique | **Spécifique Wifirst** |",
  "| Coût à l'échelle | 💸💸💸 | Maîtrisé |",
  "| Personnalisation | Limitée | **Totale** |",
  "",
  "C'est pourquoi nous avons construit **Spot** — notre plateforme d'observabilité réseau, développée 100% en interne.",
  "",
  "## Architecture globale",
  "",
  "```",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                     EDGE (par site client)                   │",
  "│  ┌──────────────────────────────────────────────────────┐   │",
  "│  │  Spot Collector (Go binary, ~15MB RAM)               │   │",
  "│  │  ├── SNMP Poller (interfaces, CPU, mem, Wi-Fi)       │   │",
  "│  │  ├── Syslog Receiver (UDP 514)                       │   │",
  "│  │  ├── Active Tester (ping, DNS, HTTP, speedtest)      │   │",
  "│  │  ├── Wi-Fi Metrics (assoc clients, RSSI, airtime)    │   │",
  "│  │  └── Streaming Telemetry (gNMI/gRPC) [nouveaux AP]   │   │",
  "│  └──────────────────────────────┬───────────────────────┘   │",
  "└─────────────────────────────────┼───────────────────────────┘",
  "                                  │ Protobuf / gzip",
  "                                  │ via MQTT ou HTTPS",
  "                                  ▼",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                      INGESTION LAYER                         │",
  "│  ┌────────────────────────────────────────────────────┐     │",
  "│  │              Apache Kafka (3 brokers)               │     │",
  "│  │  Topics:                                            │     │",
  "│  │  ├── raw.snmp.metrics     (~800K msg/min)           │     │",
  "│  │  ├── raw.syslog.events    (~200K msg/min)           │     │",
  "│  │  ├── raw.wifi.metrics     (~600K msg/min)           │     │",
  "│  │  ├── raw.active.tests     (~100K msg/min)           │     │",
  "│  │  ├── processed.alerts     (~2K msg/min)             │     │",
  "│  │  └── processed.aggregates (~50K msg/min)            │     │",
  "│  └────────────────────────┬───────────────────────────┘     │",
  "└───────────────────────────┼─────────────────────────────────┘",
  "                            ▼",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                    PROCESSING LAYER                          │",
  "│  ┌────────────────────────────────────────────────────┐     │",
  "│  │              Apache Flink Cluster                   │     │",
  "│  │  Jobs:                                              │     │",
  "│  │  ├── MetricAggregator (1min, 5min, 1h rollups)     │     │",
  "│  │  ├── AnomalyDetector (baseline dynamique)           │     │",
  "│  │  ├── EventCorrelator (multi-source)                 │     │",
  "│  │  ├── AlertEngine (scoring + dédup)                  │     │",
  "│  │  ├── SLACalculator (uptime, perf par client)        │     │",
  "│  │  └── WiFiAnalyzer (roaming, interference, capacity) │     │",
  "│  └────────────┬──────────────┬────────────────────────┘     │",
  "└───────────────┼──────────────┼──────────────────────────────┘",
  "                ▼              ▼",
  "┌──────────────────┐  ┌──────────────────┐",
  "│  TimescaleDB     │  │  S3 (cold)       │",
  "│  (hot: 90 days)  │  │  (Parquet, 2y)   │",
  "│  ├── metrics     │  │                  │",
  "│  ├── events      │  │  Queryable via   │",
  "│  ├── alerts      │  │  Trino/Presto    │",
  "│  └── aggregates  │  │                  │",
  "└────────┬─────────┘  └──────────────────┘",
  "         │",
  "         ▼",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                       API LAYER (Go)                         │",
  "│  ├── REST API (sites, devices, metrics, alerts)             │",
  "│  ├── GraphQL (dashboard queries)                            │",
  "│  ├── WebSocket (real-time updates)                          │",
  "│  └── gRPC (internal services)                               │",
  "└─────────────────────────┬───────────────────────────────────┘",
  "                          ▼",
  "┌─────────────────────────────────────────────────────────────┐",
  "│                    FRONTEND (React/TypeScript)                │",
  "│  ├── Dashboard global (carte de France, KPIs)               │",
  "│  ├── Vue site (topologie, métriques, clients)               │",
  "│  ├── Vue device (détail AP/switch, historique)              │",
  "│  ├── Alerting center (triage, acquittement, escalade)       │",
  "│  └── Reports (SLA, capacity planning, tendances)            │",
  "└─────────────────────────────────────────────────────────────┘",
  "```",
  "",
  "## Le Spot Collector : notre agent edge",
  "",
  "Le Spot Collector est un binaire Go minimaliste qui tourne sur chaque CPE (routeur/passerelle) client. Contraintes de design :",
  "",
  "- **< 15 MB RAM** — les CPE ont des ressources limitées",
  "- **< 2% CPU** — ne pas impacter le forwarding",
  "- **Résilient** — doit survivre aux reboots, pertes de connectivité",
  "- **Auto-updateable** — via notre pipeline de déploiement Ansible",
  "",
  "```go",
  "// Extrait simplifié du collector (Go)",
  "type Collector struct {",
  "    pollers    []Poller",
  "    buffer     *RingBuffer    // Buffer local en cas de perte de connectivité",
  "    transport  Transport      // MQTT ou HTTPS selon le site",
  "    compress   bool           // Protobuf + gzip",
  "}",
  "",
  "func (c *Collector) Run(ctx context.Context) error {",
  "    ticker := time.NewTicker(60 * time.Second)",
  "    defer ticker.Stop()",
  "    ",
  "    for {",
  "        select {",
  "        case <-ticker.C:",
  "            metrics := c.collectAll()",
  "            ",
  "            batch := &MetricBatch{",
  "                SiteID:    c.siteID,",
  "                Timestamp: time.Now().UnixMilli(),",
  "                Metrics:   metrics,",
  "            }",
  "            ",
  "            encoded, _ := proto.Marshal(batch)",
  "            compressed := gzip.Compress(encoded)",
  "            ",
  "            if err := c.transport.Send(compressed); err != nil {",
  "                // Perte de connectivité → buffer local",
  "                c.buffer.Push(compressed)",
  '                log.Warn("buffered locally", "size", c.buffer.Len())',
  "            }",
  "            ",
  "        case <-ctx.Done():",
  "            return c.flush() // Envoyer le buffer restant",
  "        }",
  "    }",
  "}",
  "```",
  "",
  "### Gestion de la perte de connectivité",
  "",
  "Un point crucial : nos collectors tournent sur des sites dont **la connectivité peut tomber**. Le ring buffer local stocke jusqu'à 4h de métriques. À la reconnexion, les données sont renvoyées avec leur timestamp original — pas de trou dans les graphes.",
  "",
  "```",
  "Timeline de perte de connectivité :",
  "────────────────────────────────────────────────",
  "[10:00] WAN Link Down",
  "        → Collector detecte l'échec d'envoi",
  "        → Switch mode BUFFER (stockage RAM + disk si besoin)",
  "",
  "[10:45] WAN Link Up",
  "        → Collector detecte la connectivité",
  "        → Flush du buffer (priorité FIFO)",
  "        → Envoi des métriques temps réel en parallèle",
  "",
  "[10:46] Ingestion Kafka",
  "        → TimescaleDB insère les données avec timestamp 10:00-10:45",
  "        → Grafana affiche les données rétroactivement",
  "────────────────────────────────────────────────",
  "```",
  "",
  "## Alerting intelligent avec Flink",
  "",
  "Avoir des graphes, c'est bien. Avoir des alertes exploitables, c'est mieux. Notre moteur d'alerting basé sur Flink traite les flux en temps réel pour détecter des **patterns complexes**, pas juste des seuils.",
  "",
  "### Exemple : Détection de flapping Wi-Fi",
  "",
  "Une alerte classique \"AP Down\" est inutile si l'AP redémarre toutes les 2 minutes. Flink nous permet de définir des fenêtres temporelles :",
  "",
  "```java",
  "// Logique Flink CEP (Complex Event Processing)",
  "Pattern<Event, ?> flappingPattern = Pattern.<Event>begin(\"first_down\")",
  "    .where(evt -> evt.type == AP_STATUS_DOWN)",
  "    .next(\"recovery\")",
  "    .where(evt -> evt.type == AP_STATUS_UP)",
  "    .within(Time.minutes(5))",
  "    .times(3); // 3 redémarrages en 5 minutes",
  "",
  "// Si pattern matché → Alerte critique \"AP Flapping\" + Ticket Jira auto",
  "```",
  "",
  "## Conclusion",
  "",
  "Spot traite aujourd'hui plus de **3 milliards de points de données par jour**. C'est un avantage concurrentiel majeur qui nous permet d'être proactifs plutôt que réactifs.",
  "",
  "Prochaine étape pour Spot : l'intégration de modèles ML pour la **prédiction de pannes** avant qu'elles n'arrivent (AIOps).",
  "",
  "---",
  "",
  "*Article rédigé par l'équipe Platform de Wifirst — Juillet 2025*",
].join("\n");

// ─────────────────────────────────────────────────
// Article 5: NetDevOps
// ─────────────────────────────────────────────────
const article5Content = [
  "# NetDevOps : Automatiser 50 000 équipements sans tout casser",
  "",
  "## L'ère du CLI artisanal est révolue",
  "",
  "Il fut un temps où gérer un réseau signifiait se connecter en SSH sur chaque switch, taper quelques commandes Cisco IOS, sauvegarder (`wr mem`), et passer au suivant. À l'échelle de Wifirst (15 000 sites), cette approche est impossible. Elle est lente, source d'erreurs, et non reproductible.",
  "",
  "Nous avons basculé vers une approche **NetDevOps** : traiter notre infrastructure réseau comme du code logiciel.",
  "",
  "## La stack d'automatisation",
  "",
  "Notre pipeline d'automatisation repose sur 3 piliers :",
  "",
  "1.  **Source of Truth (SoT)** : Netbox",
  "2.  **Orchestrateur** : AWX (Ansible Tower open source)",
  "3.  **Exécution** : Ansible + Python",
  "",
  "### 1. Netbox : La vérité, toute la vérité",
  "",
  "Rien n'existe dans le réseau si ce n'est pas dans Netbox. C'est notre base de données de référence pour :",
  "- Les sites et leur adresse",
  "- Les équipements (modèle, serial, IP de management)",
  "- Les connexions (câblage, ports)",
  "- Les préfixes IP et VLANs",
  "",
  "Nos scripts Ansible ne contiennent **aucune variable en dur**. Tout est dynamique, tiré de l'API Netbox via un inventaire dynamique.",
  "",
  "### 2. Ansible : L'ouvrier incatigable",
  "",
  "Nous gérons des équipements hétérogènes : Cisco, Aruba, Ruckus, Mikrotik, Dell. Ansible nous permet d'abstraire cette complexité grâce aux collections.",
  "",
  "#### Structure d'un rôle Ansible typique",
  "",
  "```yaml",
  "# roles/switch_configure/tasks/main.yml",
  "---",
  "- name: Render switch configuration",
  "  template:",
  "    src: \"{{ device_manufacturer }}.j2\"",
  "    dest: \"/tmp/configs/{{ inventory_hostname }}.conf\"",
  "",
  "- name: Push config to device (idempotent)",
  "  network_cli:",
  "    host: \"{{ ansible_host }}\"",
  "    config: \"{{ lookup('file', '/tmp/configs/' + inventory_hostname + '.conf') }}\"",
  "    diff: yes",
  "  notify: save_config",
  "```",
  "",
  "### Le défi de l'idempotence réseau",
  "",
  "En gestion de serveurs, `apt install nginx` est idempotent : si c'est déjà là, il ne fait rien. En réseau, c'est plus dur. Pousser une config peut couper votre propre accès SSH !",
  "",
  "Nous utilisons une stratégie de **\"config replacement\"** ou de **\"declarative state\"** quand c'est possible, plutôt que d'envoyer des commandes ligne à ligne.",
  "",
  "## CI/CD pour le réseau",
  "",
  "Avant de pousser une config sur 5000 switchs, on veut être sûr qu'elle marche. Voici notre pipeline GitLab CI :",
  "",
  "```",
  "┌──────────┐    ┌──────────┐    ┌──────────┐    ┌──────────┐",
  "│  Lint    │───►│  Test    │───►│  Dry-Run │───►│  Deploy  │",
  "│ (Yamllint│    │ (GNS3 /  │    │ (Check   │    │ (Prod)   │",
  "│  Ansible-│    │  Batfish)│    │  mode)   │    │          │",
  "│  lint)   │    │          │    │          │    │          │",
  "└──────────┘    └──────────┘    └──────────┘    └──────────┘",
  "```",
  "",
  "### Batfish : Valider avant de déployer",
  "",
  "Nous utilisons **Batfish** pour simuler l'impact d'un changement de config (ACL, routage) sans toucher au matériel réel. C'est un \"jumeau numérique\" du réseau.",
  "",
  "```python",
  "# Test Batfish dans la CI",
  "def test_acl_permits_dns(snap):",
  "    result = bfq.testFilters(",
  "        headers=HeaderConstraints(dstPort=53, protocol='udp'),",
  "        action='deny'",
  "    ).answer(snap)",
  "    assert len(result.frame()) == 0, \"DNS traffic is blocked!\"",
  "```",
  "",
  "## Cas d'usage : La campagne de mise à jour firmware",
  "",
  "Mettre à jour 12 000 APs manuellement prendrait des mois. Avec notre playbook Ansible `firmware_upgrade.yml` :",
  "",
  "1.  **Pre-check** : Vérifie l'espace disque, la charge CPU, les clients connectés.",
  "2.  **Drain** : Migre les clients vers les APs voisins (802.11v).",
  "3.  **Upgrade** : Upload image + reboot (rolling update, max 10% du site à la fois).",
  "4.  **Post-check** : Vérifie la version, les associations OSPF, le nombre de clients.",
  "5.  **Rollback** : Si le post-check échoue, retour automatique à l'ancienne version.",
  "",
  "Résultat : **99.8% de succès** sur 12 000 APs en 3 nuits, zéro intervention humaine.",
  "",
  "## Conclusion",
  "",
  "Le NetDevOps n'est pas magique, c'est de la rigueur. Mais une fois en place, il transforme l'équipe réseau : moins de \"pompiers\", plus d'architectes.",
  "",
  "---",
  "",
  "*Article rédigé par l'équipe NetDev de Wifirst — Août 2025*",
].join("\n");

// ─────────────────────────────────────────────────
// Seed Logic
// ─────────────────────────────────────────────────

const articles = [
  {
    slug: "bienvenue-sur-le-blog-tech-wifirst",
    title: "Bienvenue sur le blog tech Wifirst",
    content: article1Content,
    excerpt: "Pourquoi nous lançons ce blog, qui nous sommes, et ce que vous allez y trouver. Plongée dans les coulisses de l'ingénierie Wifirst.",
    category: "Culture",
    tags: ["Wifirst", "Engineering", "Culture", "Recrutement"],
    coverImage: "/images/blog/article1-stack.png",
    featured: true,
    author: {
      name: "David Berkowicz",
      role: "CTO",
      avatar: "https://ui-avatars.com/api/?name=David+Berkowicz&background=0D8ABC&color=fff"
    },
    readTime: 5,
    publishedAt: Timestamp.fromDate(new Date("2025-09-01T10:00:00Z"))
  },
  {
    slug: "wifi-6e-retour-experience",
    title: "Wi-Fi 6E : retour d'expérience sur un déploiement à grande échelle",
    content: article2Content,
    excerpt: "Comment nous avons migré 500+ sites vers le Wi-Fi 6E. Analyse de performance, challenges techniques et impact sur l'expérience utilisateur.",
    category: "Wi-Fi",
    tags: ["Wi-Fi 6E", "Radio", "6GHz", "Engineering"],
    coverImage: "/images/blog/article2-spectrum.png",
    featured: false,
    author: {
      name: "Équipe Radio",
      role: "NetDev Squad",
      avatar: "https://ui-avatars.com/api/?name=Radio+Team&background=6B21A8&color=fff"
    },
    readTime: 8,
    publishedAt: Timestamp.fromDate(new Date("2025-09-15T14:30:00Z"))
  },
  {
    slug: "zero-trust-network-architecture",
    title: "Sécuriser un réseau d'entreprise : notre approche Zero Trust",
    content: article3Content,
    excerpt: "Fini le château fort. Découvrez comment nous implémentons le Zero Trust (802.1X, micro-segmentation, NAC) sur des milliers de sites.",
    category: "Security",
    tags: ["Zero Trust", "Security", "Network", "802.1X", "PCI-DSS"],
    coverImage: "/images/blog/article3-zerotrust.png",
    featured: false,
    author: {
      name: "Équipe Sécurité",
      role: "SecOps Squad",
      avatar: "https://ui-avatars.com/api/?name=Security+Team&background=DC2626&color=fff"
    },
    readTime: 10,
    publishedAt: Timestamp.fromDate(new Date("2025-10-02T09:15:00Z"))
  },
  {
    slug: "spot-monitoring-at-scale",
    title: "Comment nous monitorons 15 000 sites en temps réel avec Spot",
    content: article4Content,
    excerpt: "Architecture de Spot, notre plateforme d'observabilité maison : Go, Kafka, Flink et TimescaleDB pour ingérer 2 millions de métriques par minute.",
    category: "Observability",
    tags: ["Monitoring", "Go", "Kafka", "Flink", "TimescaleDB"],
    coverImage: "/images/blog/article4-spot.png",
    featured: true,
    author: {
      name: "Équipe Platform",
      role: "Core Infra Squad",
      avatar: "https://ui-avatars.com/api/?name=Platform+Team&background=059669&color=fff"
    },
    readTime: 12,
    publishedAt: Timestamp.fromDate(new Date("2025-10-20T11:00:00Z"))
  }
];

async function seed() {
  console.log("🚀 Starting seed...");
  
  for (const article of articles) {
    try {
      console.log(`Writing article: ${article.title}`);
      await setDoc(doc(db, "articles", article.slug), article);
      console.log(`✅ Success: ${article.slug}`);
    } catch (error) {
      console.error(`❌ Error writing ${article.slug}:`, error);
    }
  }

  console.log("✨ Seed complete!");
  process.exit(0);
}

seed();
